### ISSUE TITLE
psd.cli fails with text-extract from hierarchical layer psd

### ISSUE THREAD

**Issue by h1618** [kartsims/psd-cli#3]
tried psd-cli on a test.psd of mine with multiple layers in groups of groups, and see following error:

```
$ psd test.psd -t
Processing test.psd ...
TypeError: Cannot read property 'replace' of null
  at /usr/lib/node_modules/psd-cli/bin/psd.js:57:38
  at Array.forEach (native)
  at /usr/lib/node_modules/psd-cli/bin/psd.js:53:12
  at Array.forEach (native)
  at /usr/lib/node_modules/psd-cli/bin/psd.js:49:34
  at lib$rsvp$$internal$$tryCatch (/usr/lib/node_modules/psd-cli/node_modules/rsvp/dist/rsvp.js:493:16)
  at lib$rsvp$$internal$$invokeCallback (/usr/lib/node_modules/psd-cli/node_modules/rsvp/dist/rsvp.js:505:17)
  at lib$rsvp$$internal$$publish (/usr/lib/node_modules/psd-cli/node_modules/rsvp/dist/rsvp.js:476:11)
  at lib$rsvp$asap$$flush (/usr/lib/node_modules/psd-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
  at _combinedTickCallback (internal/process/next_tick.js:67:7)
  at process._tickCallback (internal/process/next_tick.js:98:9)
```

seems layer.extractText() returned something that has no text property?!?
btw I use node/v7.2.1 on linux x64

**Comment by kartsims** [comment]
Hmm interesting, I guess the "goups of groups" use case hasn't been tested yet

Could you please send me a PSD file that would trigger such error ? kartsims@gmail.com or upload it somewhere and send the link here

**Comment by kartsims** [comment]
Please re-open if you can submit an example

**Comment by digimiles** [comment]
Thanks kartsims, your latest release fixes this issue!
